#Configuracion del Simulador de Supermercado
#Thu Jul 02 14:53:26 GMT-04:00 2026
articulos.cliente.max=30
articulos.cliente.min=1
duracion.real.segundos=20
limite.cliente.rapido=10
limite.clientes=0
mostrar.detalle.clientes=true
mostrar.estadisticas.avanzadas=true
num.cajas.normales=4
num.cajas.rapidas=2
probabilidad.llegada.cliente=40
tiempo.caja.normal.max=8
tiempo.caja.normal.min=4
tiempo.caja.rapida.max=5
tiempo.caja.rapida.min=2
tiempo.simulado.horas=12
