package com.supermercado.domain.cooperativa.event;

public enum TipoEvento {
    SIMULACION_INICIADA,
    SIMULACION_PAUSADA,
    SIMULACION_REANUDADA,
    SIMULACION_DETENIDA,
    SIMULACION_REINICIADA,
    SIMULACION_FINALIZADA,
    SOCIO_GENERADO,
    SOCIO_ASIGNADO,
    SOCIO_ATENDIDO,
    FASE_PRINCIPAL_FINALIZADA,
    FASE_REZAGADOS_INICIADA,
    ESTADISTICAS_ACTUALIZADAS,
    DIA_INICIADO,
    DIA_FINALIZADO,
    SIMULACION_MENSUAL_FINALIZADA
}